import { jsPDF } from 'jspdf';
import { Receipt } from '@/types';
import { SCHOOL_CONFIG } from '@/lib/schoolConfig';

/**
 * Generates a PDF receipt on the server-side.
 * Branded for a single school using SCHOOL_CONFIG.
 */
export const generateServerReceiptPDF = (receipt: Receipt): Buffer => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const pageWidth = doc.internal.pageSize.getWidth();

    // ── Header ─────────────────────────────────────────────────────────────────
    doc.setFillColor(0, 0, 0);
    doc.rect(0, 0, pageWidth, 45, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(SCHOOL_CONFIG.name, 20, 22);

    doc.setFontSize(9);
    doc.setTextColor(251, 191, 36);
    doc.text('OFFICIAL PAYMENT RECEIPT', 20, 30);

    doc.setFontSize(7);
    doc.setTextColor(180, 180, 180);
    doc.text(SCHOOL_CONFIG.address, 20, 37);
    doc.text(`${SCHOOL_CONFIG.phone}  |  ${SCHOOL_CONFIG.email}`, 20, 42);

    // ── Reset text colour ───────────────────────────────────────────────────────
    doc.setTextColor(0, 0, 0);

    // ── Receipt Details ─────────────────────────────────────────────────────────
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Receipt Details', 20, 62);
    doc.setDrawColor(251, 191, 36);
    doc.line(20, 64, 65, 64);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`Receipt #: ${receipt.receiptNumber}`, 20, 72);
    doc.text(`Date: ${new Date(receipt.paidAt).toLocaleDateString('en-IN')}`, 20, 78);
    doc.text(`Transaction ID: ${receipt.transactionId}`, 20, 84);

    // ── Student Info ────────────────────────────────────────────────────────────
    doc.setFont('helvetica', 'bold');
    doc.text('Student Information', 120, 62);
    doc.line(120, 64, 168, 64);

    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${receipt.studentName}`, 120, 72);
    doc.text(`ID: ${receipt.studentId}`, 120, 78);
    doc.text(`Class: ${receipt.class}`, 120, 84);

    // ── Items Table ─────────────────────────────────────────────────────────────
    doc.setFillColor(245, 245, 245);
    doc.rect(20, 102, pageWidth - 40, 10, 'F');
    doc.setFont('helvetica', 'bold');
    doc.text('Description', 25, 108);
    doc.text('Amount', pageWidth - 50, 108);

    doc.setFont('helvetica', 'normal');
    doc.line(20, 112, pageWidth - 20, 112);
    doc.text(receipt.feeType, 25, 122);
    doc.text(`INR ${receipt.amountPaid.toLocaleString('en-IN')}`, pageWidth - 50, 122);
    doc.line(20, 128, pageWidth - 20, 128);

    // ── Total ───────────────────────────────────────────────────────────────────
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Total Paid', pageWidth - 80, 144);
    doc.text(`₹ ${receipt.amountPaid.toLocaleString('en-IN')}`, pageWidth - 50, 144);

    // ── Footer ──────────────────────────────────────────────────────────────────
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('This is a computer-generated receipt. No signature is required.', 20, 272);
    doc.text(
        `Generated by: ${receipt.generatedBy}  |  System ID: ${receipt.receiptId}  |  ${SCHOOL_CONFIG.name}`,
        20, 277
    );

    // Yellow footer bar
    doc.setFillColor(251, 191, 36);
    doc.rect(0, 287, pageWidth, 10, 'F');

    // Return as Buffer
    const pdfOutput = doc.output('arraybuffer');
    return Buffer.from(pdfOutput);
};
